/**
 * Style-guide asset generator (contract M8). Hand-placed pixel grids,
 * authored in ASCII (1 char = 1 px), rendered to PNG. Reproducible:
 * rerun via `npm run gen:styleguide`. Approved assets are never
 * overwritten afterward — version new files instead.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PNG } from 'pngjs';
import { Rng } from '../src/core/rng';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = join(ROOT, 'assets/styleguide');
mkdirSync(OUT, { recursive: true });

type Palette = Record<string, [number, number, number, number]>;

const hex = (h: string, a = 255): [number, number, number, number] => [
  parseInt(h.slice(0, 2), 16),
  parseInt(h.slice(2, 4), 16),
  parseInt(h.slice(4, 6), 16),
  a,
];

/** Master OHMFRONT ramps — sun-bleached Texas on GBA limits. */
export const RAMPS: Record<string, string[]> = {
  caliche: ['f8f0dc', 'e0d0b0', 'c0a880', '907850', '584830'],
  rust: ['f0b070', 'd08040', 'a85828', '703818', '401c10'],
  ember: ['fff8e0', 'f8d878', 'e8a040', 'c86830', '883818'],
  steel: ['c8c0b0', '948c80', '6e6660', '4a4440', '2a2624'],
  mesquite: ['c8c878', '98a048', '687830', '405020', '283414'],
  sky: ['f8e8c0', 'e8c890', 'd8a868', 'b07840', '785030'],
};

function writePng(name: string, width: number, height: number, paint: (set: (x: number, y: number, c: [number, number, number, number]) => void) => void, prompt: string): void {
  const png = new PNG({ width, height });
  const set = (x: number, y: number, c: [number, number, number, number]): void => {
    if (x < 0 || y < 0 || x >= width || y >= height) return;
    const i = (y * width + x) * 4;
    png.data[i] = c[0];
    png.data[i + 1] = c[1];
    png.data[i + 2] = c[2];
    png.data[i + 3] = c[3];
  };
  paint(set);
  writeFileSync(join(OUT, `${name}.png`), PNG.sync.write(png));
  writeFileSync(
    join(OUT, `${name}.prompt.txt`),
    `OHMFRONT style-guide asset "${name}"\nGenerated by: tools/gen-styleguide.ts (npm run gen:styleguide)\nAuthor: Claude (hand-placed pixel grids / deterministic procedure)\nRules: docs/style-guide.md — Gen 3 GBA, <=16 colors incl. transparency,\n240x160 presentation, light from top-left, dark outline with sel-out.\n${prompt}\n`,
  );
  console.log(`wrote ${name}.png (${width}x${height})`);
}

function sprite(name: string, rows: string[], palette: Palette, canvas: number, prompt: string): void {
  const h = rows.length;
  const w = Math.max(...rows.map((r) => r.length));
  if (w > canvas || h > canvas) throw new Error(`${name} ${w}x${h} exceeds ${canvas}`);
  const ox = Math.floor((canvas - w) / 2);
  const oy = canvas - h - Math.floor(canvas / 16); // grounded near bottom, Gen 3 stage feel
  writePng(name, canvas, canvas, (set) => {
    rows.forEach((row, y) => {
      for (let x = 0; x < row.length; x++) {
        const ch = row[x] ?? '.';
        if (ch === '.') continue;
        const c = palette[ch];
        if (!c) throw new Error(`${name}: no palette entry for "${ch}"`);
        set(ox + x, oy + y, c);
      }
    });
  }, prompt);
}

// ---------------------------------------------------------------- Charkit
// THERM starter Ohmlet: hand-welded furnace box on treads, ember window.
const charkitPal: Palette = {
  k: hex('2a1c14'),
  d: hex('703818'),
  r: hex('a85828'),
  o: hex('d08040'),
  O: hex('f0b070'),
  s: hex('4a4440'),
  t: hex('6e6660'),
  h: hex('948c80'),
  b: hex('2a2624'),
  B: hex('4a4440'),
  C: hex('6e6660'),
  y: hex('e8a040'),
  g: hex('f8d878'),
  w: hex('fff8e0'),
};
const charkit = [
  '.............khhk...............',
  '.............ksttk..............',
  '.............kstsk..............',
  '..........kkkksttkkkk...........',
  '........kkddddddddddddkk........',
  '......kkdrrrrrrrrrrrrrrdkk......',
  '.....kdrroooooooooooooorrdk.....',
  '....kdroOOooooooooooooOoordk....',
  '....kdroOooooooooooooooordk.....',
  '....kdrooooookkkkkkooooordk.....',
  '....kdroooookgyyyygkoooordk.....',
  '....kdroooookygwwgykoooordk.....',
  '....kdroooookywggwykoooordk.....',
  '....kdroooookgyyyygkoooordk.....',
  '....kdrooooookkkkkkooooordk.....',
  '....kdroooooooooooooooooordk....',
  '....kdrroooooooooooooooorrdk....',
  '.....kdrrooooooooooooooordk.....',
  '.....kkdrrrrrrrrrrrrrrrrdkk.....',
  '......kkddddddddddddddddkk......',
  '....kkbbbbbbbbbbbbbbbbbbbbkk....',
  '...kbBBCBBCBBCBBCBBCBBCBBBBbk...',
  '...kbBCBBCBBCBBCBBCBBCBBCBBbk...',
  '...kbBBCBBCBBCBBCBBCBBCBBBBbk...',
  '....kkbbbbbbbbbbbbbbbbbbbbkk....',
  '......kkkkkkkkkkkkkkkkkkkk......',
];

// ---------------------------------------------------------------- Toastlet
// THERM wild common: chrome toaster, glowing slots, stubby feet.
const toastletPal: Palette = {
  k: hex('2a2624'),
  s: hex('4a4440'),
  t: hex('6e6660'),
  h: hex('948c80'),
  H: hex('c8c0b0'),
  w: hex('fff8e0'),
  y: hex('f8d878'),
  o: hex('e8a040'),
  r: hex('a85828'),
  d: hex('703818'),
};
const toastlet = [
  '.......kkkkkkkkkkkkkk.......',
  '.....kkhHHHHHhhhHHHhhkk.....',
  '....khHkkkkkhhhkkkkkhhhk....',
  '...khHkyyyyykhkyyyyykhhhk...',
  '...khkyooooykhkyoooyykhhk...',
  '...khkkkkkkkhhhkkkkkkkhhk...',
  '..khHhhhhhhhhhhhhhhhhhhhhk..',
  '..khHhhwwhhhhhhhhhhhhhhhtk..',
  '..khHhwkkwhhhhhhwkkwhhhhtk..',
  '..khHhwkkwhhhhhhwkkwhhhhtk..',
  '..khHhhwwhhhhhhhhwwhhhhhtk..',
  '..khHhhhhhhhkkkhhhhhhhhhtk..',
  '..khHhhhhhhkdddkhhhhhhhhtk..',
  '..khHhhhhhhhkkkhhhhhhhhhtk..',
  '..khhhhhhhhhhhhhhhhhhhhttk..',
  '...khtttttttttttttttttttk...',
  '....kkssssssssssssssssskk...',
  '......kssk........kssk......',
  '......kssk........kssk......',
  '.......kk..........kk.......',
];

// ---------------------------------------------------------------- Filaglow
// OPTIC wild: bulb Ohmlet, filament eye, screw-base body. LUMEN line.
const filaglowPal: Palette = {
  k: hex('2a2624'),
  w: hex('fff8e0'),
  g: hex('f8d878'),
  y: hex('e8a040'),
  o: hex('c86830'),
  s: hex('4a4440'),
  t: hex('6e6660'),
  h: hex('948c80'),
  H: hex('c8c0b0'),
};
const filaglow = [
  '.......kkkkkk.......',
  '.....kkwwwwwwkk.....',
  '....kwwwwwwwwwwk....',
  '...kwwwwgggwwwwwk...',
  '...kwwggggggggwwk...',
  '..kwwgggykkyggggwk..',
  '..kwwggykggkygggwk..',
  '..kwwggykggkygggwk..',
  '..kwwgggykkygggwwk..',
  '..kwwwggggggggwwwk..',
  '...kwwwgggggggwwk...',
  '...kkwwwwgggwwwkk...',
  '....kkwwwwwwwwkk....',
  '......kkwwwwkk......',
  '......khHHHHhk......',
  '.....kthhhhhhtk.....',
  '.....kshHHHHhsk.....',
  '.....kthhhhhhtk.....',
  '.....kshHHHHhsk.....',
  '......kthhhhtk......',
  '.......kssssk.......',
  '........kkkk........',
];

// 16x16 overworld micros (Gen 3 proportions: big head silhouette)
const charkitMicro = [
  '......kk........',
  '...kkkskkkk.....',
  '..kdrrrrrrdk....',
  '..kdrokkoordk...',
  '..kdrkgykordk...',
  '..kdrkywkordk...',
  '..kdrokkoordk...',
  '..kdrrrrrrrdk...',
  '..kkbbbbbbkk....',
  '..kbCBCBCBbk....',
  '...kkkkkkkk.....',
];
const toastletMicro = [
  '...kkkkkkkk.....',
  '..khyykyyhk.....',
  '..khkkhkkhk.....',
  '..khhhhhhhk.....',
  '..khwkwkwhk.....',
  '..khhhhhhhk.....',
  '...kktttkk......',
  '...kk...kk......',
];
const filaglowMicro = [
  '....kkkk........',
  '...kwwwwk.......',
  '..kwgkkgwk......',
  '..kwgkkgwk......',
  '..kwggggwk......',
  '...kwwwwk.......',
  '...khHHhk.......',
  '...kshhsk.......',
  '....kkkk........',
];

sprite('ohm_charkit_battle_v1', charkit, charkitPal, 64, 'Charkit, THERM starter (Bench), 64x64 battle sprite, 14 colors. Furnace box, ember-grate face, treads.');
sprite('ohm_toastlet_battle_v1', toastlet, toastletPal, 64, 'Toastlet, wild THERM common, 64x64 battle sprite, 10 colors. Chrome toaster, glowing slots, stubby feet.');
sprite('ohm_filaglow_battle_v1', filaglow, filaglowPal, 64, 'Filaglow, wild OPTIC (LUMEN line), 64x64 battle sprite, 9 colors. Bulb with filament eyes, screw-base body.');
sprite('ohm_charkit_overworld_v1', charkitMicro, charkitPal, 16, 'Charkit 16x16 overworld form.');
sprite('ohm_toastlet_overworld_v1', toastletMicro, toastletPal, 16, 'Toastlet 16x16 overworld form.');
sprite('ohm_filaglow_overworld_v1', filaglowMicro, filaglowPal, 16, 'Filaglow 16x16 overworld form.');

// ------------------------------------------------------------- tile strip
const tile = (set: (x: number, y: number, c: [number, number, number, number]) => void, ox: number, base: string[], speckle: string[], density: number, seed: number): void => {
  const rng = new Rng(seed);
  for (let y = 0; y < 16; y++)
    for (let x = 0; x < 16; x++) set(ox + x, y, hex(base[(x + y) % base.length] ?? 'ffffff'));
  for (let i = 0; i < density; i++) {
    set(ox + rng.int(0, 15), rng.int(0, 15), hex(speckle[rng.int(0, speckle.length - 1)] ?? 'ffffff'));
  }
};

writePng('tileset_field_strip_v1', 16 * 8, 16, (set) => {
  tile(set, 0, ['e0d0b0', 'e0d0b0', 'd8c8a8'], ['c0a880', 'f8f0dc', '907850'], 26, 11); // caliche dirt
  tile(set, 16, ['c8c878', 'c0c070'], ['98a048', '687830', 'e0d0b0'], 30, 22); // dry grass
  tile(set, 32, ['98a048', '90a048'], ['687830', '405020', 'c8c878'], 44, 33); // tall grass (encounter)
  tile(set, 48, ['b0a090', 'a89888'], ['6e6660', 'c8c0b0', '4a4440'], 22, 44); // cracked road
  tile(set, 64, ['6e6660', '645c54'], ['4a4440', '948c80', '2a2624'], 36, 55); // rubble wall
  tile(set, 80, ['948c80', '8c8478'], ['a85828', '4a4440', 'c8c0b0'], 40, 66); // debris pile
  tile(set, 96, ['e0d0b0', 'd8c8a8'], ['703818', 'a85828', '584830'], 18, 77); // fence line
  tile(set, 112, ['6e6660', '787068'], ['4878a0', '948c80', '2a2624'], 20, 88); // garage pad
}, 'Field tileset strip v1: caliche dirt, dry grass, tall grass, cracked road, rubble wall, debris, fence line, garage pad. 16x16 each.');

// ------------------------------------------------------------- palette sheet
const rampNames = Object.keys(RAMPS);
writePng('palette_ramps_v1', 5 * 12, rampNames.length * 12, (set) => {
  rampNames.forEach((name, row) => {
    (RAMPS[name] ?? []).forEach((h, col) => {
      for (let y = 0; y < 12; y++) for (let x = 0; x < 12; x++) set(col * 12 + x, row * 12 + y, hex(h));
    });
  });
}, `Master ramps, top to bottom: ${rampNames.join(', ')}. 5 steps each, light source top-left.`);
