/**
 * HD Ohm rework (npm run gen:sprites:hd).
 *
 * Renders every Ohm design (the single source in gen-sprites.ts) through the
 * supersampling smoother: the 64px hard-edged GBA sprite becomes a 96x96 HD
 * sprite whose Bayer dither has dissolved into smooth gradients and whose
 * silhouette is anti-aliased — pushing the whole roster toward the soft,
 * painted feel of the cattle-town reference, uniformly.
 *
 * Output: <num>_front_hd.png + src/data/sprite-manifest-hd.ts. The engine
 * shows these once the 480x320 resolution bump lands; the 64px set keeps the
 * game running meanwhile.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PNG } from 'pngjs';
import { hdSmooth } from './spritekit';
import { FRONT_BUILDERS } from './gen-sprites';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = join(ROOT, 'public/sprites/ohms');
mkdirSync(OUT, { recursive: true });

const TARGET = 96;
const SUPERSAMPLE = 5; // KxK samples per output pixel

const nums = Object.keys(FRONT_BUILDERS)
  .map(Number)
  .sort((a, b) => a - b);

for (const num of nums) {
  const builder = FRONT_BUILDERS[num];
  if (!builder) continue;
  const small = builder(); // 64x64 design
  const hd = hdSmooth(small, TARGET, SUPERSAMPLE); // 96x96 smooth
  const png = new PNG({ width: TARGET, height: TARGET });
  png.data.set(hd.data);
  writeFileSync(join(OUT, `${num}_front_hd.png`), PNG.sync.write(png));
  writeFileSync(
    join(OUT, `${num}_front_hd.prompt.txt`),
    `OHMFRONT HD sprite "${num}_front_hd" (${TARGET}x${TARGET})\n` +
      `Generated by tools/gen-sprites-hd.ts (npm run gen:sprites:hd)\n` +
      `Author: Claude. Original design, supersampled HD rework of the GBA sprite\n` +
      `(${SUPERSAMPLE}x${SUPERSAMPLE} area-downsample: dither -> gradients, AA edges).\n`,
  );
}

writeFileSync(
  join(ROOT, 'src/data/sprite-manifest-hd.ts'),
  `// AUTO-GENERATED by tools/gen-sprites-hd.ts — do not edit by hand.\n` +
    `/** Species numbers with a generated HD (96x96) battle front sprite. */\n` +
    `export const HD_FRONT_SPRITES: readonly number[] = ${JSON.stringify(nums)};\n` +
    `export const hasHdFront = (n: number): boolean => HD_FRONT_SPRITES.includes(n);\n`,
);

console.log(`HD-reworked ${nums.length} fronts at ${TARGET}x${TARGET} -> public/sprites/ohms/`);
