// AUTO-GENERATED by tools/gen-sprites.ts — do not edit by hand.
/** Species numbers with a generated battle front sprite. */
export const FRONT_SPRITES: readonly number[] = [1,4,7,10,12,15,18,19,21,30,32,41];
/** Species numbers with a generated battle back sprite. */
export const BACK_SPRITES: readonly number[] = [1,4,7];
export const hasFront = (n: number): boolean => FRONT_SPRITES.includes(n);
export const hasBack = (n: number): boolean => BACK_SPRITES.includes(n);
