// AUTO-GENERATED by tools/assets/kit-ohms.ts — do not edit by hand.
/** Species numbers with a generated HD (96x96) battle front sprite. */
export const HD_FRONT_SPRITES: readonly number[] = Array.from({ length: 150 }, (_, i) => i + 1);
/** Species numbers with a generated HD (96x96) battle back sprite. */
export const HD_BACK_SPRITES: readonly number[] = Array.from({ length: 150 }, (_, i) => i + 1);
export const hasHdFront = (n: number): boolean => HD_FRONT_SPRITES.includes(n);
export const hasHdBack = (n: number): boolean => HD_BACK_SPRITES.includes(n);
