// AUTO-GENERATED by tools/gen-sprites-hd.ts — do not edit by hand.
/** Species numbers with a generated HD (96x96) battle front sprite. */
export const HD_FRONT_SPRITES: readonly number[] = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48];
/** Species numbers with a generated HD (96x96) battle back sprite. */
export const HD_BACK_SPRITES: readonly number[] = [1,2,3,4,5,6,7,8,9];
export const hasHdFront = (n: number): boolean => HD_FRONT_SPRITES.includes(n);
export const hasHdBack = (n: number): boolean => HD_BACK_SPRITES.includes(n);
