// AUTO-GENERATED by tools/gen-sprites.ts — do not edit by hand.
/** Species numbers with a generated battle front sprite. */
export const FRONT_SPRITES: readonly number[] = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48];
/** Species numbers with a generated battle back sprite. */
export const BACK_SPRITES: readonly number[] = [1,2,3,4,5,6,7,8,9];
export const hasFront = (n: number): boolean => FRONT_SPRITES.includes(n);
export const hasBack = (n: number): boolean => BACK_SPRITES.includes(n);
